### ISSUE TITLE
Doesn't appear as payment method on frontend, and error when trying to pair from command line.

### ISSUE THREAD

**Issue by 218420** [storefront-bvba/magento2-btcpay-module#1]
Magento 2.3.3. New install. 

bin/magento btcpay:pair (PAIRING CODE)

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to BTCPayServer\Client\Request::setPort() must be of the type integer, null given, called in /var/www/html/vendor/btcpayserver/btcpayserver-php-client/src/BTCPayServer/Client/Client.php on line 643 and defined in /var/www/html/vendor/btcpayserver/btcpayserver-php-client/src/BTCPayServer/Client/Request.php:137
Stack trace:
#0 /var/www/html/vendor/btcpayserver/btcpayserver-php-client/src/BTCPayServer/Client/Client.php(643): BTCPayServer\Client\Request->setPort(NULL)
#1 /var/www/html/vendor/btcpayserver/btcpayserver-php-client/src/BTCPayServer/Client/Client.php(491): BTCPayServer\Client\Client->createNewRequest()
#2 /var/www/html/vendor/storefront/magento2-btcpay-module/Model/BTCPay/BTCPayService.php(184): BTCPayServer\Client\Client->createToken(Array)
#3 /var/www/html/vendor/storefront/magento2-btcpay-module/Console/Command/Pair.php(48): Storefront\BTCPay\Model\BTCPay\BTCPayService->pair(0, 'PAIRING CODE')
#4 /var/www/html/vendor/symfony/console/Command/Command.php(255): Storefr in /var/www/html/vendor/btcpayserver/btcpayserver-php-client/src/BTCPayServer/Client/Request.php on line 137

**Comment by woutersamaey** [comment]
When configuring your BTCPay Server URL, just add the port number to the URL.
A fix is bring prepared in the underlaying API, but this should help.

**Comment by 218420** [comment]
Hi, Wouter.  I'm not expert, but I was looking through the code and it looks like a lot of hard work, so thanks for everything! 

I was able to get it up and running. It works as expected.. until the payment is 'complete'. 

Then it gets stuck in the 'processing' order status. Creating a shipment does not complete the order. An invoice is created, notes are made to the order as the BTCpayserver invoice status is updated, and the invoice shows as paid when the order is 'complete', but the sales numbers aren't showing in the lifetime totals or the revenue on the dashboard. 

Test orders made with the 'check and money order' payment method/module work as expected, and are 'completed' when an invoice and shipment are made. I'm not sure if I'm missing a config option somewhere for the BTCpay module?

Also, If I leave the order status set to 'magento default' on the backend in the BTCpay module configuration, then the orders status gets set to empty, and it gets stuck with an empty status and won't close out or complete the order either.
