### ISSUE TITLE
Static js not deployed

### ISSUE THREAD

**Issue by ecoshops** [storefront-bvba/magento2-btcpay-module#2]
Magento ver. 2.3.2
PHP 7.2

Console:
GET [HOST]/pub/static/frontend/Magento/blank/en_US/Storefront_BTCPay/js/btcpay/config.js net::ERR_ABORTED 404 (Not Found)

Error while deploying static content:
/var/report/debug.log:
main.CRITICAL: Unable to resolve the source file for 'frontend/Magento/blank/en_US/Storefront_BTCPay/js/btcpay/config.js' [] []

Thanks.

**Comment by woutersamaey** [comment]
Fixed + bumped version to 1.0.2

**Comment by ecoshops** [comment]
Thanks Sir, works flawlessly.
