### ISSUE TITLE
Order status wont 'complete'

### ISSUE THREAD

**Issue by 218420** [storefront-bvba/magento2-btcpay-module#3]
Magento 2.3.3 
New installation

If I allow the module to set the order status, an invoice is created as expected. Payment and order status is updated as expected throughout the process as well.

But the order gets stuck in the "processing" status. Creating a shipment does not move order to 'complete' status.

And 

The sales numbers aren't showing in the lifetime totals or the revenue on the dashboard.

Using the magento default status in the module, leaves the order status empty throughout the payment confirmation process. Creating a shipment does not move order to 'complete' status in this scenario either. 

Any ideas?

**Comment by woutersamaey** [comment]
Magento needs and invoice and a shipment for the order to become complete. I haven’t tested yet, but I see no reason why it shouldn’t work. Our module only handles the payment method and invoice creation. No other aspects of Magento are affected. Are you sure you have an invoice (with invoice status paid) and a shipment for all items?

**Comment by 218420** [comment]
As far as I can tell, everything is invoiced, paid, and shipped. I don't have the option to create additional payments/invoices or shipments. 

The invoice payment is not reflecting on the dashboard though, so maybe magento still thinks it's upaid somewhere?

![Screen Shot 2019-12-28 at 9 56 58 AM](https://user-images.githubusercontent.com/58526270/71547171-b7c21700-2959-11ea-9191-0a3d9d6af3bb.png)

![Screen Shot 2019-12-28 at 9 58 39 AM](https://user-images.githubusercontent.com/58526270/71547173-c8728d00-2959-11ea-83ba-d6bf7a3756b6.png)

![Screen Shot 2019-12-28 at 9 57 34 AM](https://user-images.githubusercontent.com/58526270/71547174-d4f6e580-2959-11ea-9e11-493666822d44.png)

![Screen Shot 2019-12-28 at 9 57 43 AM](https://user-images.githubusercontent.com/58526270/71547183-ecce6980-2959-11ea-968b-b0d390e8cb7b.png)

**Comment by woutersamaey** [comment]
I’ll need to investigate a bit further. Thanks for the detailed feedback!

**Comment by 218420** [comment]
Sounds good. Let me know what you find. I'll start using this module ASAP.

**Comment by woutersamaey** [comment]
Do you have a developer who can debug the method \Magento\Sales\Model\Order\StateResolver::getStateForOrder() ? The clue to finding out this issue is there I believe.

My guess is this will be a specific issue related to your case and not necessarily an issue with this module. Judging from your screenshots, everything looks normal, so further investigation would be needed.

If you don't have a (skilled & experienced) developer, I am available for hire.

**Comment by 218420** [comment]
**SOLVED**

Changing /Model/BTCPay.php      $stateObject->setState(\Magento\Sales\Model\Order::STATE_PENDING_PAYMENT)->setStatus(\Magento\Sales\Model\Order::STATE_PENDING_PAYMENT);

TO:

$stateObject->setState(\Magento\Sales\Model\Order::STATE_NEW)->setStatus(\Magento\Sales\Model\Order::STATE_PENDING_PAYMENT);

Fixes this issue for me.

This allows an order to "Complete" after it is shipped- And updates the Lifetime sales total- after shipping the order.

Setting it to Order::STATE_PROCESSING works as expected as well. It updates the Lifetime sales total after the BTCPay invoice is paid, but before the order is shipped. 

Setting Order::STATE_PENDING_PAYMENT sets the DB table: sales_order.state to 'pending_payment', and it is never set to 'new' or updated to 'processing' later after the invoice is paid, so it gets stuck.

I'm new to github, how do I fix this in the code? Leaving it as Order::STATE_PENDING_PAYMENT would be fine- I guess- as long as the state was updated somewhere further along in the process... I haven't got that far along in the process yet. I'm learning magento as I go.

**Comment by woutersamaey** [comment]
@218420 thanks for the detailed feedback. I have applied the fix and released this as version 1.0.3
